services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    command: sh -c "./entrypoint.sh"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - API_VERSION=${API_VERSION}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    networks:
      - mydocker-apps-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    networks:
      - mydocker-apps-network

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "password"
    networks:
      - mydocker-apps-network

networks:
  default:
    driver: bridge
  mydocker-apps-network:
    external: true
volumes:
  mongo_data:
